server:
  port: 8100

spring:
  application:
    name: 'CONFIG-SERVER'

  datasource:
    url: ${DB_MICRO_URL}
    username: ${DB_MICRO_USERNAME}
    password: ${DB_MICRO_PWD}
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    config:
      server:
        jdbc:
          sql: "select `key`, value from properties where application=? and profile=? and label=?"



