spring:
  application:
    name: 'CONFIG-SERVER'
  cloud:
    config:
      server:
        jdbc:
          sql: "select `key`, value from properties where application=? and profile=? and label=?"



