version: "3"

services:
    jce_java:
        build: ./docker-jce-jre
        image: pronter/jce-java
        read_only: true
        command: echo "jce java"
        environment:
            - TZ=Asia/Shanghai



#    redis:
#            image: redis:3.2.9
#            ports:
#                - "6378:6378"
#            hostname: prontera-redis
#            volumes:
#                - "./docker-redis/share/:/data/"
#            environment:
#                - TZ=Asia/Shanghai
#    solar_mysql:
#        image: mysql:5.7.17
#        ports:
#            - "3306:3306"
#        volumes:
#            - "./docker-mysql/share/:/share/"
#            - "./docker-mysql/db/:/docker-entrypoint-initdb.d/:ro"
#            - "./docker-mysql/master/lib/:/var/lib/mysql/"
#            - "./docker-mysql/master/log/:/var/log/mysql/"
#            - "./docker-mysql/master/conf.d/:/etc/mysql/mysql.conf.d/"
#        environment:
#            - MYSQL_ROOT_PASSWORD=123456
