
# 开发工具，禁止复制到别处环境
codex:
  jdbc:
    url: ${DB_MICRO_URL:jdbc:mysql://localhost:3306/codex?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false}
    username: ${DB_MICRO_USERNAME}
    password: ${DB_MICRO_PWD}
    driverClassName: com.mysql.jdbc.Driver
  package:
    entity-path: pub.codex.db.core.entity
    mapper-path: pub.codex.db.core.mapper
    mapperXML-path: mapper
    service-path: pub.codex.db.core.service
    serviceImpl-path: pub.codex.db.core.service.impl
    controller-path: pub.codex.core.controller
  prefix: sys_
apix:
  controllerPackage: pub.codex.core.controller

