
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      default:  #数据源1
        url: ${DB_MICRO_URL:jdbc:mysql://localhost:3306/codex?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false}
        username: ${DB_MICRO_USERNAME}
        password: ${DB_MICRO_PWD}
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

# 开发工具，禁止复制到别处环境
codex:
  jdbc:
    url: ${DB_MICRO_URL:jdbc:mysql://localhost:3306/codex?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false}
    username: ${DB_MICRO_USERNAME}
    password: ${DB_MICRO_PWD}
    driverClassName: com.mysql.jdbc.Driver
  package:
    entity-path: pub.codex.db.core.entity
    mapper-path: pub.codex.db.core.mapper
    mapperXML-path: mapper
    service-path: pub.codex.core.service
    serviceImpl-path: pub.codex.service.impl
    controller-path: pub.codex.core.controller
  prefix: sys_
apix:
  controllerPackage: pub.codex.core.controller

